const NOT_FOUND_STATUS_CODE = 404
const UNAUTHORIZED_STATUS_CODE = 401
const SUCCESS_STATUS_CODE = 200

module.exports = {
    SUCCESS_STATUS_CODE,
    NOT_FOUND_STATUS_CODE,
    UNAUTHORIZED_STATUS_CODE,
}